-- DIRZY STORE - Supabase setup
-- 1) Create a Supabase project.
-- 2) Open SQL Editor and run this whole file.
-- 3) Replace the admin email below with your own email BEFORE running it.
-- 4) Create an Auth user with that same email/password in Authentication > Users.

create table if not exists public.admins (
  email text primary key
);

-- CHANGE THIS EMAIL:
insert into public.admins(email) values ('GANTI_EMAIL_ADMIN@example.com')
on conflict (email) do nothing;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  uid text not null,
  name text not null,
  level integer default 0,
  rank text default '-',
  bundle text default '-',
  price integer not null default 0,
  image_url text,
  available boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;
alter table public.products enable row level security;

-- Public visitors can view products.
create policy "public can view products"
on public.products for select
to anon, authenticated
using (true);

-- Only emails listed in admins can modify products.
create policy "admins can insert products"
on public.products for insert
to authenticated
with check (
  exists (select 1 from public.admins a
          where lower(a.email) = lower((select auth.jwt()->>'email')))
);

create policy "admins can update products"
on public.products for update
to authenticated
using (
  exists (select 1 from public.admins a
          where lower(a.email) = lower((select auth.jwt()->>'email')))
)
with check (
  exists (select 1 from public.admins a
          where lower(a.email) = lower((select auth.jwt()->>'email')))
);

create policy "admins can delete products"
on public.products for delete
to authenticated
using (
  exists (select 1 from public.admins a
          where lower(a.email) = lower((select auth.jwt()->>'email')))
);

-- Admins can check their own allow-list row.
create policy "admins can view admin list"
on public.admins for select
to authenticated
using (
  lower(email) = lower((select auth.jwt()->>'email'))
);

-- Storage bucket for product photos.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

create policy "public can view product images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'product-images');

create policy "admins can upload product images"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'product-images'
  and exists (select 1 from public.admins a
              where lower(a.email) = lower((select auth.jwt()->>'email')))
);

create policy "admins can update product images"
on storage.objects for update
to authenticated
using (
  bucket_id = 'product-images'
  and exists (select 1 from public.admins a
              where lower(a.email) = lower((select auth.jwt()->>'email')))
);

create policy "admins can delete product images"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'product-images'
  and exists (select 1 from public.admins a
              where lower(a.email) = lower((select auth.jwt()->>'email')))
);

-- Optional starter product:
insert into public.products (uid,name,level,rank,bundle,price,available)
values ('123456789','ID FF Cantik #001',65,'Heroic','120+ bundle',150000,true);
